name: Scraper & Summary

on:
  schedule:
    - cron: "0 9 * * 1-5"
jobs:
  build:
    runs-on: ubuntu-22.04  # 명시적으로 Ubuntu 버전 설정
    steps:
    - uses: actions/checkout@v3  # checkout 최신 버전(v3) 사용
    - name: Set up Python
      uses: actions/setup-python@v4  # setup-python 최신 버전(v4) 사용
      with:
        python-version: 3.10  # 사용 가능한 Python 버전 (3.10)으로 변경
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Run Scripts
      env:
        OPEN_API_KEY: ${{ secrets.OPEN_API_KEY }}  # 환경 변수로 API 키 전달
      run: |
        python scrap_and_summary.py --api_key $OPEN_API_KEY
    - name: Configure Git
      run: |
        git config --local user.email "asdfg6548@syuin.ac.kr"
        git config --local user.name "asdfg6548"
    - name: Commit and Push Changes
      run: |
        git add .
        git commit -m "Auto - daily report summary" || echo "No changes to commit"
        git push origin master
